<datapower-configuration version="3"><export-details><description>Exported Configuration</description><user>twu04</user><domain>DIT-Smartcore-Services</domain><comment/><product-id>5725</product-id><product>IDG</product><display-product>IDG</display-product><model>IBM DataPower Gateway</model><display-model>IBM DataPower Gateway</display-model><device-name>ciambccudtdpw01</device-name><serial-number>0000000</serial-number><firmware-version>IDG.2018.4.1.3hy</firmware-version><display-firmware-version>IDG.2018.4.1.3hy</display-firmware-version><firmware-build>307450hy</firmware-build><delivery-type>LTS</delivery-type><firmware-timestamp>2019/03/23 13:30:08</firmware-timestamp><current-date>2020-04-29</current-date><current-time>14:58:05 EDT</current-time><reset-date>2020-03-31</reset-date><reset-time>18:23:56 EDT</reset-time><login-message/><custom-ui-file>local:///DP_Banner.xml</custom-ui-file></export-details><interface-data/><configuration domain="DIT-Smartcore-Services"><CryptoKey name="DataPowerBMOFGKey" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<Filename>sharedcert:///iambccdpdit.bmogc.net.pfx</Filename>
<Password>DITChannel2020</Password>
<PasswordAlias>off</PasswordAlias></CryptoKey><CryptoCertificate name="DataPowerBMOFGCert" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<Filename>sharedcert:///iambccdpdit.bmogc.net.pfx</Filename>
<Password>DITChannel2020</Password>
<PasswordAlias>off</PasswordAlias>
<IgnoreExpiration>off</IgnoreExpiration></CryptoCertificate><CryptoIdentCred name="DataPowerIDCredForChannel" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<Key class="CryptoKey">DataPowerBMOFGKey</Key>
<Certificate class="CryptoCertificate">DataPowerBMOFGCert</Certificate></CryptoIdentCred><CryptoCertificate name="BMOMSIntermediateCert" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<Filename>sharedcert:///MS_QA_issuing_CA1.cer</Filename>
<PasswordAlias>off</PasswordAlias>
<IgnoreExpiration>off</IgnoreExpiration></CryptoCertificate><CryptoCertificate name="testcert" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<Filename>sharedcert:///DP_Shakedown.cer</Filename>
<PasswordAlias>off</PasswordAlias>
<IgnoreExpiration>off</IgnoreExpiration></CryptoCertificate><CryptoValCred name="BMOMSSignerValCred" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<Certificate class="CryptoCertificate">BMOMSIntermediateCert</Certificate>
<Certificate class="CryptoCertificate">testcert</Certificate>
<CertValidationMode>legacy</CertValidationMode>
<UseCRL>on</UseCRL>
<RequireCRL>off</RequireCRL>
<CRLDPHandling>ignore</CRLDPHandling>
<InitialPolicySet>2.5.29.32.0</InitialPolicySet>
<ExplicitPolicy>off</ExplicitPolicy>
<CheckDates>on</CheckDates></CryptoValCred><SSLServerProfile name="@@SERVICE_NAME@@SSLServerProfile" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<Protocols>
<SSLv3>off</SSLv3>
<TLSv1d0>off</TLSv1d0>
<TLSv1d1>off</TLSv1d1>
<TLSv1d2>on</TLSv1d2></Protocols>
<Ciphers>ECDHE_ECDSA_WITH_AES_256_GCM_SHA384</Ciphers>
<Ciphers>ECDHE_RSA_WITH_AES_256_GCM_SHA384</Ciphers>
<Ciphers>ECDHE_ECDSA_WITH_AES_256_CBC_SHA384</Ciphers>
<Ciphers>ECDHE_RSA_WITH_AES_256_CBC_SHA384</Ciphers>
<Ciphers>ECDHE_ECDSA_WITH_AES_256_CBC_SHA</Ciphers>
<Ciphers>ECDHE_RSA_WITH_AES_256_CBC_SHA</Ciphers>
<Ciphers>DHE_DSS_WITH_AES_256_GCM_SHA384</Ciphers>
<Ciphers>DHE_RSA_WITH_AES_256_GCM_SHA384</Ciphers>
<Ciphers>DHE_RSA_WITH_AES_256_CBC_SHA256</Ciphers>
<Ciphers>DHE_DSS_WITH_AES_256_CBC_SHA256</Ciphers>
<Ciphers>DHE_RSA_WITH_AES_256_CBC_SHA</Ciphers>
<Ciphers>DHE_DSS_WITH_AES_256_CBC_SHA</Ciphers>
<Ciphers>RSA_WITH_AES_256_GCM_SHA384</Ciphers>
<Ciphers>RSA_WITH_AES_256_CBC_SHA256</Ciphers>
<Ciphers>RSA_WITH_AES_256_CBC_SHA</Ciphers>
<Ciphers>ECDHE_ECDSA_WITH_AES_128_GCM_SHA256</Ciphers>
<Ciphers>ECDHE_RSA_WITH_AES_128_GCM_SHA256</Ciphers>
<Ciphers>ECDHE_ECDSA_WITH_AES_128_CBC_SHA256</Ciphers>
<Ciphers>ECDHE_RSA_WITH_AES_128_CBC_SHA256</Ciphers>
<Ciphers>ECDHE_ECDSA_WITH_AES_128_CBC_SHA</Ciphers>
<Ciphers>ECDHE_RSA_WITH_AES_128_CBC_SHA</Ciphers>
<Ciphers>DHE_DSS_WITH_AES_128_GCM_SHA256</Ciphers>
<Ciphers>DHE_RSA_WITH_AES_128_GCM_SHA256</Ciphers>
<Ciphers>DHE_RSA_WITH_AES_128_CBC_SHA256</Ciphers>
<Ciphers>DHE_DSS_WITH_AES_128_CBC_SHA256</Ciphers>
<Ciphers>DHE_RSA_WITH_AES_128_CBC_SHA</Ciphers>
<Ciphers>DHE_DSS_WITH_AES_128_CBC_SHA</Ciphers>
<Ciphers>RSA_WITH_AES_128_GCM_SHA256</Ciphers>
<Ciphers>RSA_WITH_AES_128_CBC_SHA256</Ciphers>
<Ciphers>RSA_WITH_AES_128_CBC_SHA</Ciphers>
<Ciphers>ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA</Ciphers>
<Ciphers>ECDHE_RSA_WITH_3DES_EDE_CBC_SHA</Ciphers>
<Ciphers>DHE_RSA_WITH_3DES_EDE_CBC_SHA</Ciphers>
<Ciphers>DHE_DSS_WITH_3DES_EDE_CBC_SHA</Ciphers>
<Ciphers>RSA_WITH_3DES_EDE_CBC_SHA</Ciphers>
<Idcred class="CryptoIdentCred">DataPowerIDCredForChannel</Idcred>
<RequestClientAuth>on</RequestClientAuth>
<RequireClientAuth>on</RequireClientAuth>
<ValidateClientCert>on</ValidateClientCert>
<SendClientAuthCAList>off</SendClientAuthCAList>
<Valcred class="CryptoValCred">BMOMSSignerValCred</Valcred>
<Caching>on</Caching>
<CacheTimeout>300</CacheTimeout>
<CacheSize>20</CacheSize>
<SSLOptions>
<max-duration>off</max-duration>
<max-renegotiation>off</max-renegotiation></SSLOptions>
<MaxSSLDuration>60</MaxSSLDuration>
<NumberOfRenegotiationAllowed>0</NumberOfRenegotiationAllowed>
<ProhibitResumeOnReneg>off</ProhibitResumeOnReneg>
<Compression>off</Compression>
<AllowLegacyRenegotiation>off</AllowLegacyRenegotiation>
<PreferServerCiphers>on</PreferServerCiphers>
<EllipticCurves>secp521r1</EllipticCurves>
<EllipticCurves>secp384r1</EllipticCurves>
<EllipticCurves>secp256k1</EllipticCurves>
<EllipticCurves>secp256r1</EllipticCurves></SSLServerProfile><HTTPSSourceProtocolHandler name="@@SERVICE_NAME@@HttpsFSH" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<UserSummary>@@SERVICE_SUMMARY@@</UserSummary>
<LocalAddress>Data-Env1</LocalAddress>
<LocalPort>@@SERVICEFSH_PORT@@</LocalPort>
<HTTPVersion>HTTP/1.1</HTTPVersion>
<AllowedFeatures>
<HTTP-1.0>on</HTTP-1.0>
<HTTP-1.1>on</HTTP-1.1>
<HTTP-2.0>on</HTTP-2.0>
<POST>on</POST>
<GET>on</GET>
<PUT>on</PUT>
<HEAD>on</HEAD>
<OPTIONS>on</OPTIONS>
<TRACE>on</TRACE>
<DELETE>on</DELETE>
<CONNECT>off</CONNECT>
<CustomMethods>on</CustomMethods>
<QueryString>on</QueryString>
<FragmentIdentifiers>on</FragmentIdentifiers>
<DotDot>off</DotDot>
<CmdExe>off</CmdExe></AllowedFeatures>
<PersistentConnections>on</PersistentConnections>
<MaxPersistentConnectionsReuse>0</MaxPersistentConnectionsReuse>
<AllowCompression>off</AllowCompression>
<AllowWebSocketUpgrade>off</AllowWebSocketUpgrade>
<WebSocketIdleTimeout>0</WebSocketIdleTimeout>
<MaxURLLen>16384</MaxURLLen>
<MaxTotalHdrLen>128000</MaxTotalHdrLen>
<MaxHdrCount>0</MaxHdrCount>
<MaxNameHdrLen>0</MaxNameHdrLen>
<MaxValueHdrLen>0</MaxValueHdrLen>
<MaxQueryStringLen>0</MaxQueryStringLen>
<CredentialCharset>protocol</CredentialCharset>
<SSLServerConfigType>server</SSLServerConfigType>
<SSLServer class="SSLServerProfile">@@SERVICE_NAME@@SSLServerProfile</SSLServer>
<HTTP2MaxStreams>100</HTTP2MaxStreams>
<HTTP2MaxFrameSize>16384</HTTP2MaxFrameSize>
<HTTP2StreamHeader>off</HTTP2StreamHeader>
<ChunkedEncoding>on</ChunkedEncoding></HTTPSSourceProtocolHandler><LoadBalancerGroup name="HubCredentialServicesV2LBG" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<Algorithm>round-robin</Algorithm>
<Damp>120</Damp>
<NeverReturnSickMember>off</NeverReturnSickMember>
<LBGroupMembers>
<Server>isambccld3was01.srv.bmogc.net</Server>
<Weight>1</Weight>
<MappedPort>0</MappedPort>
<Activity/>
<HealthPort/>
<LBMemberState>enabled</LBMemberState></LBGroupMembers>
<LBGroupMembers>
<Server>dummy2</Server>
<Weight>1</Weight>
<MappedPort>0</MappedPort>
<Activity/>
<HealthPort/>
<LBMemberState>enabled</LBMemberState></LBGroupMembers>
<LBGroupMembers>
<Server>dummy3</Server>
<Weight>1</Weight>
<MappedPort>0</MappedPort>
<Activity/>
<HealthPort/>
<LBMemberState>enabled</LBMemberState></LBGroupMembers>
<LBGroupMembers>
<Server>dummy4</Server>
<Weight>1</Weight>
<MappedPort>0</MappedPort>
<Activity/>
<HealthPort/>
<LBMemberState>enabled</LBMemberState></LBGroupMembers>
<LBGroupMembers>
<Server>dummy5</Server>
<Weight>1</Weight>
<MappedPort>0</MappedPort>
<Activity/>
<HealthPort/>
<LBMemberState>enabled</LBMemberState></LBGroupMembers>
<LBGroupMembers>
<Server>dummy6</Server>
<Weight>1</Weight>
<MappedPort>0</MappedPort>
<Activity/>
<HealthPort/>
<LBMemberState>enabled</LBMemberState></LBGroupMembers>
<LBGroupMembers>
<Server>dummy7</Server>
<Weight>1</Weight>
<MappedPort>0</MappedPort>
<Activity/>
<HealthPort/>
<LBMemberState>enabled</LBMemberState></LBGroupMembers>
<LBGroupMembers>
<Server>dummy8</Server>
<Weight>1</Weight>
<MappedPort>0</MappedPort>
<Activity/>
<HealthPort/>
<LBMemberState>enabled</LBMemberState></LBGroupMembers>
<LBGroupMembers>
<Server>dummy9</Server>
<Weight>1</Weight>
<MappedPort>0</MappedPort>
<Activity/>
<HealthPort/>
<LBMemberState>enabled</LBMemberState></LBGroupMembers>
<TryEveryServerBeforeFailing>on</TryEveryServerBeforeFailing>
<LBGroupChecks>
<Active>on</Active>
<URI>/</URI>
<Port>9443</Port>
<SSL>TCPConnection</SSL>
<Post>on</Post>
<Input>store:///healthcheck.xml</Input>
<Timeout>10</Timeout>
<Frequency>180</Frequency>
<XPath>/</XPath>
<Filter>store:///healthcheck.xsl</Filter>
<SSLProxyProfile/>
<EnforceTimeout>off</EnforceTimeout>
<IndependentChecks>off</IndependentChecks>
<GatewayScriptChecks>off</GatewayScriptChecks>
<GatewayScriptReqMethod>GET</GatewayScriptReqMethod>
<GatewayScriptCustomReqMethod/>
<GatewayScriptReqDoc>store:///healthcheck.json</GatewayScriptReqDoc>
<GatewayScriptReqContentType>application/json</GatewayScriptReqContentType>
<GatewayScriptRspHandlerMetadata/>
<GatewayScriptRspHandler>store:///healthcheck.js</GatewayScriptRspHandler>
<TCPConnectionType>Full</TCPConnectionType>
<SSLClientConfigType>proxy</SSLClientConfigType>
<SSLClient/></LBGroupChecks>
<MasqueradeMember>off</MasqueradeMember></LoadBalancerGroup><HTTPUserAgent name="@@SERVICE_NAME@@UserAgent" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<MaxRedirects>8</MaxRedirects>
<Timeout>300</Timeout></HTTPUserAgent><XMLManager name="@@SERVICE_NAME@@XMLManager" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<CacheSize>256</CacheSize>
<SHA1Caching>on</SHA1Caching>
<StaticDocumentCalls>on</StaticDocumentCalls>
<SearchResults>on</SearchResults>
<SupportTxWarn>off</SupportTxWarn>
<VirtualServers class="LoadBalancerGroup">HubCredentialServicesV2LBG</VirtualServers>
<Memoization>on</Memoization>
<ParserLimitsBytesScanned>6291456</ParserLimitsBytesScanned>
<ParserLimitsElementDepth>512</ParserLimitsElementDepth>
<ParserLimitsAttributeCount>128</ParserLimitsAttributeCount>
<ParserLimitsMaxNodeSize>33554432</ParserLimitsMaxNodeSize>
<ParserLimitsForbidExternalReferences>on</ParserLimitsForbidExternalReferences>
<ParserLimitsExternalReferences>forbid</ParserLimitsExternalReferences>
<ParserLimitsMaxPrefixes>1024</ParserLimitsMaxPrefixes>
<ParserLimitsMaxNamespaces>1024</ParserLimitsMaxNamespaces>
<ParserLimitsMaxLocalNames>60000</ParserLimitsMaxLocalNames>
<DocCacheMaxDocs>5000</DocCacheMaxDocs>
<DocCacheSize>0</DocCacheSize>
<DocMaxWrites>32768</DocMaxWrites>
<UserAgent class="HTTPUserAgent">@@SERVICE_NAME@@UserAgent</UserAgent></XMLManager><Matching name="ALL" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<MatchRules>
<Type>url</Type>
<HttpTag/>
<HttpValue/>
<Url>*</Url>
<ErrorCode/>
<XPATHExpression/>
<Method>default</Method>
<CustomMethod/></MatchRules>
<MatchWithPCRE>off</MatchWithPCRE>
<CombineWithOr>off</CombineWithOr></Matching><StylePolicyAction name="@@SERVICE_NAME@@Policy_RequestRule_xform_1" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<Type>xform</Type>
<Input>NULL</Input>
<Transform>local:///dpcommon/xsl/bmo-transaction-log.xsl</Transform>
<ParseSettingsReference>
<URL/>
<Literal/>
<Default/></ParseSettingsReference>
<ParseMetricsResultType>none</ParseMetricsResultType>
<TransformLanguage>none</TransformLanguage>
<ActionDebug persisted="false">off</ActionDebug>
<Output>NULL</Output>
<NamedInOutLocationType>default</NamedInOutLocationType>
<SSLClientConfigType>proxy</SSLClientConfigType>
<OutputType>default</OutputType>
<Transactional>off</Transactional>
<SOAPValidation>body</SOAPValidation>
<SQLSourceType>static</SQLSourceType>
<JWSVerifyStripSignature>on</JWSVerifyStripSignature>
<Asynchronous>off</Asynchronous>
<ResultsMode>first-available</ResultsMode>
<RetryCount>0</RetryCount>
<RetryInterval>1000</RetryInterval>
<MultipleOutputs>off</MultipleOutputs>
<IteratorType>XPATH</IteratorType>
<Timeout>0</Timeout>
<MethodRewriteType>GET</MethodRewriteType>
<MethodType>POST</MethodType>
<MethodType2>POST</MethodType2></StylePolicyAction><StylePolicyAction name="@@SERVICE_NAME@@Policy_RequestRule_xform_2" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<Type>xform</Type>
<Input>NULL</Input>
<Transform>local:///mpg/SmartcoreServicesV1/@@SERVICE_NAME@@MPG/xsl/ClientAuthentication.xsl</Transform>
<ParseSettingsReference>
<URL/>
<Literal/>
<Default/></ParseSettingsReference>
<ParseMetricsResultType>none</ParseMetricsResultType>
<TransformLanguage>none</TransformLanguage>
<ActionDebug persisted="false">off</ActionDebug>
<Output>NULL</Output>
<NamedInOutLocationType>default</NamedInOutLocationType>
<SSLClientConfigType>proxy</SSLClientConfigType>
<OutputType>default</OutputType>
<Transactional>off</Transactional>
<SOAPValidation>body</SOAPValidation>
<SQLSourceType>static</SQLSourceType>
<JWSVerifyStripSignature>on</JWSVerifyStripSignature>
<Asynchronous>off</Asynchronous>
<ResultsMode>first-available</ResultsMode>
<RetryCount>0</RetryCount>
<RetryInterval>1000</RetryInterval>
<MultipleOutputs>off</MultipleOutputs>
<IteratorType>XPATH</IteratorType>
<Timeout>0</Timeout>
<MethodRewriteType>GET</MethodRewriteType>
<MethodType>POST</MethodType>
<MethodType2>POST</MethodType2></StylePolicyAction><StylePolicyAction name="@@SERVICE_NAME@@Policy_RequestRule_xform_3" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<Type>xform</Type>
<Input>NULL</Input>
<Transform>local:///mpg/SmartcoreServicesV1/@@SERVICE_NAME@@MPG/xsl/payloadSizeValidation.xsl</Transform>
<ParseSettingsReference>
<URL/>
<Literal/>
<Default/></ParseSettingsReference>
<ParseMetricsResultType>none</ParseMetricsResultType>
<TransformLanguage>none</TransformLanguage>
<ActionDebug persisted="false">off</ActionDebug>
<Output>NULL</Output>
<NamedInOutLocationType>default</NamedInOutLocationType>
<SSLClientConfigType>proxy</SSLClientConfigType>
<OutputType>default</OutputType>
<Transactional>off</Transactional>
<SOAPValidation>body</SOAPValidation>
<SQLSourceType>static</SQLSourceType>
<JWSVerifyStripSignature>on</JWSVerifyStripSignature>
<Asynchronous>off</Asynchronous>
<ResultsMode>first-available</ResultsMode>
<RetryCount>0</RetryCount>
<RetryInterval>1000</RetryInterval>
<MultipleOutputs>off</MultipleOutputs>
<IteratorType>XPATH</IteratorType>
<Timeout>0</Timeout>
<MethodRewriteType>GET</MethodRewriteType>
<MethodType>POST</MethodType>
<MethodType2>POST</MethodType2></StylePolicyAction><StylePolicyAction name="@@SERVICE_NAME@@Policy_RequestRule_xform_4" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<Type>xform</Type>
<Input>NULL</Input>
<Transform>local:///mpg/SmartcoreServicesV1/@@SERVICE_NAME@@MPG/xsl/process.xsl</Transform>
<ParseSettingsReference>
<URL/>
<Literal/>
<Default/></ParseSettingsReference>
<ParseMetricsResultType>none</ParseMetricsResultType>
<TransformLanguage>none</TransformLanguage>
<ActionDebug persisted="false">off</ActionDebug>
<Output>NULL</Output>
<NamedInOutLocationType>default</NamedInOutLocationType>
<SSLClientConfigType>proxy</SSLClientConfigType>
<OutputType>default</OutputType>
<Transactional>off</Transactional>
<SOAPValidation>body</SOAPValidation>
<SQLSourceType>static</SQLSourceType>
<JWSVerifyStripSignature>on</JWSVerifyStripSignature>
<Asynchronous>off</Asynchronous>
<ResultsMode>first-available</ResultsMode>
<RetryCount>0</RetryCount>
<RetryInterval>1000</RetryInterval>
<MultipleOutputs>off</MultipleOutputs>
<IteratorType>XPATH</IteratorType>
<Timeout>0</Timeout>
<MethodRewriteType>GET</MethodRewriteType>
<MethodType>POST</MethodType>
<MethodType2>POST</MethodType2></StylePolicyAction><StylePolicyAction name="@@SERVICE_NAME@@Policy_RequestRule_results_0" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<Type>results</Type>
<Input>INPUT</Input>
<ParseSettingsReference>
<URL/>
<Literal/>
<Default/></ParseSettingsReference>
<ParseMetricsResultType>none</ParseMetricsResultType>
<TransformLanguage>none</TransformLanguage>
<ActionDebug persisted="false">off</ActionDebug>
<NamedInOutLocationType>default</NamedInOutLocationType>
<SSLClientConfigType>proxy</SSLClientConfigType>
<OutputType>default</OutputType>
<Transactional>off</Transactional>
<SOAPValidation>body</SOAPValidation>
<SQLSourceType>static</SQLSourceType>
<JWSVerifyStripSignature>on</JWSVerifyStripSignature>
<Asynchronous>off</Asynchronous>
<ResultsMode>first-available</ResultsMode>
<RetryCount>0</RetryCount>
<RetryInterval>1000</RetryInterval>
<MultipleOutputs>off</MultipleOutputs>
<IteratorType>XPATH</IteratorType>
<Timeout>0</Timeout>
<MethodRewriteType>GET</MethodRewriteType>
<MethodType>POST</MethodType>
<MethodType2>POST</MethodType2></StylePolicyAction><StylePolicyRule name="@@SERVICE_NAME@@Policy_RequestRule" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<Actions class="StylePolicyAction">@@SERVICE_NAME@@Policy_RequestRule_xform_1</Actions>
<Actions class="StylePolicyAction">@@SERVICE_NAME@@Policy_RequestRule_xform_2</Actions>
<Actions class="StylePolicyAction">@@SERVICE_NAME@@Policy_RequestRule_xform_3</Actions>
<Actions class="StylePolicyAction">@@SERVICE_NAME@@Policy_RequestRule_xform_4</Actions>
<Actions class="StylePolicyAction">@@SERVICE_NAME@@Policy_RequestRule_results_0</Actions>
<Direction>request-rule</Direction>
<InputFormat>none</InputFormat>
<OutputFormat>none</OutputFormat>
<NonXMLProcessing>on</NonXMLProcessing>
<Unprocessed>off</Unprocessed></StylePolicyRule><StylePolicyAction name="@@SERVICE_NAME@@Policy_ResponseRule_xform_1" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<Type>xform</Type>
<Input>NULL</Input>
<Transform>local:///dpcommon/xsl/bmo-transaction-log.xsl</Transform>
<ParseSettingsReference>
<URL/>
<Literal/>
<Default/></ParseSettingsReference>
<ParseMetricsResultType>none</ParseMetricsResultType>
<TransformLanguage>none</TransformLanguage>
<ActionDebug persisted="false">off</ActionDebug>
<Output>NULL</Output>
<NamedInOutLocationType>default</NamedInOutLocationType>
<SSLClientConfigType>proxy</SSLClientConfigType>
<OutputType>default</OutputType>
<Transactional>off</Transactional>
<SOAPValidation>body</SOAPValidation>
<SQLSourceType>static</SQLSourceType>
<JWSVerifyStripSignature>on</JWSVerifyStripSignature>
<Asynchronous>off</Asynchronous>
<ResultsMode>first-available</ResultsMode>
<RetryCount>0</RetryCount>
<RetryInterval>1000</RetryInterval>
<MultipleOutputs>off</MultipleOutputs>
<IteratorType>XPATH</IteratorType>
<Timeout>0</Timeout>
<MethodRewriteType>GET</MethodRewriteType>
<MethodType>POST</MethodType>
<MethodType2>POST</MethodType2></StylePolicyAction><StylePolicyAction name="@@SERVICE_NAME@@Policy_ResponseRule_xform_2" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<Type>xform</Type>
<Input>NULL</Input>
<Transform>local:///dpcommon/xsl/setResponseCode.xsl</Transform>
<ParseSettingsReference>
<URL/>
<Literal/>
<Default/></ParseSettingsReference>
<ParseMetricsResultType>none</ParseMetricsResultType>
<TransformLanguage>none</TransformLanguage>
<ActionDebug persisted="false">off</ActionDebug>
<Output>NULL</Output>
<NamedInOutLocationType>default</NamedInOutLocationType>
<SSLClientConfigType>proxy</SSLClientConfigType>
<OutputType>default</OutputType>
<Transactional>off</Transactional>
<SOAPValidation>body</SOAPValidation>
<SQLSourceType>static</SQLSourceType>
<JWSVerifyStripSignature>on</JWSVerifyStripSignature>
<Asynchronous>off</Asynchronous>
<ResultsMode>first-available</ResultsMode>
<RetryCount>0</RetryCount>
<RetryInterval>1000</RetryInterval>
<MultipleOutputs>off</MultipleOutputs>
<IteratorType>XPATH</IteratorType>
<Timeout>0</Timeout>
<MethodRewriteType>GET</MethodRewriteType>
<MethodType>POST</MethodType>
<MethodType2>POST</MethodType2></StylePolicyAction><StylePolicyAction name="@@SERVICE_NAME@@Policy_ResponseRule_results_1" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<Type>results</Type>
<Input>INPUT</Input>
<ParseSettingsReference>
<URL/>
<Literal/>
<Default/></ParseSettingsReference>
<ParseMetricsResultType>none</ParseMetricsResultType>
<TransformLanguage>none</TransformLanguage>
<ActionDebug persisted="false">off</ActionDebug>
<NamedInOutLocationType>default</NamedInOutLocationType>
<SSLClientConfigType>proxy</SSLClientConfigType>
<OutputType>default</OutputType>
<Transactional>off</Transactional>
<SOAPValidation>body</SOAPValidation>
<SQLSourceType>static</SQLSourceType>
<JWSVerifyStripSignature>on</JWSVerifyStripSignature>
<Asynchronous>off</Asynchronous>
<ResultsMode>first-available</ResultsMode>
<RetryCount>0</RetryCount>
<RetryInterval>1000</RetryInterval>
<MultipleOutputs>off</MultipleOutputs>
<IteratorType>XPATH</IteratorType>
<Timeout>0</Timeout>
<MethodRewriteType>GET</MethodRewriteType>
<MethodType>POST</MethodType>
<MethodType2>POST</MethodType2></StylePolicyAction><StylePolicyRule name="@@SERVICE_NAME@@Policy_ResponseRule" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<Actions class="StylePolicyAction">@@SERVICE_NAME@@Policy_ResponseRule_xform_1</Actions>
<Actions class="StylePolicyAction">@@SERVICE_NAME@@Policy_ResponseRule_xform_2</Actions>
<Actions class="StylePolicyAction">@@SERVICE_NAME@@Policy_ResponseRule_results_1</Actions>
<Direction>response-rule</Direction>
<InputFormat>none</InputFormat>
<OutputFormat>none</OutputFormat>
<NonXMLProcessing>on</NonXMLProcessing>
<Unprocessed>off</Unprocessed></StylePolicyRule><StylePolicyAction name="@@SERVICE_NAME@@Policy_rule_Error_xform_1" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<Type>xform</Type>
<Input>NULL</Input>
<Transform>local:///dpcommon/xsl/bmo-transaction-log.xsl</Transform>
<ParseSettingsReference>
<URL/>
<Literal/>
<Default/></ParseSettingsReference>
<ParseMetricsResultType>none</ParseMetricsResultType>
<TransformLanguage>none</TransformLanguage>
<ActionDebug persisted="false">off</ActionDebug>
<Output>NULL</Output>
<NamedInOutLocationType>default</NamedInOutLocationType>
<SSLClientConfigType>proxy</SSLClientConfigType>
<OutputType>default</OutputType>
<Transactional>off</Transactional>
<SOAPValidation>body</SOAPValidation>
<SQLSourceType>static</SQLSourceType>
<JWSVerifyStripSignature>on</JWSVerifyStripSignature>
<Asynchronous>off</Asynchronous>
<ResultsMode>first-available</ResultsMode>
<RetryCount>0</RetryCount>
<RetryInterval>1000</RetryInterval>
<MultipleOutputs>off</MultipleOutputs>
<IteratorType>XPATH</IteratorType>
<Timeout>0</Timeout>
<MethodRewriteType>GET</MethodRewriteType>
<MethodType>POST</MethodType>
<MethodType2>POST</MethodType2></StylePolicyAction><StylePolicyAction name="@@SERVICE_NAME@@Policy_rule_Error_xform_2" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<Type>xform</Type>
<Input>NULL</Input>
<Transform>local:///mpg/SmartcoreServicesV1/@@SERVICE_NAME@@MPG/xsl/chooseMessageType.xsl</Transform>
<ParseSettingsReference>
<URL/>
<Literal/>
<Default/></ParseSettingsReference>
<ParseMetricsResultType>none</ParseMetricsResultType>
<TransformLanguage>none</TransformLanguage>
<ActionDebug persisted="false">off</ActionDebug>
<Output>dp_var1</Output>
<NamedInOutLocationType>default</NamedInOutLocationType>
<SSLClientConfigType>proxy</SSLClientConfigType>
<OutputType>default</OutputType>
<Transactional>off</Transactional>
<SOAPValidation>body</SOAPValidation>
<SQLSourceType>static</SQLSourceType>
<JWSVerifyStripSignature>on</JWSVerifyStripSignature>
<Asynchronous>off</Asynchronous>
<ResultsMode>first-available</ResultsMode>
<RetryCount>0</RetryCount>
<RetryInterval>1000</RetryInterval>
<MultipleOutputs>off</MultipleOutputs>
<IteratorType>XPATH</IteratorType>
<Timeout>0</Timeout>
<MethodRewriteType>GET</MethodRewriteType>
<MethodType>POST</MethodType>
<MethodType2>POST</MethodType2></StylePolicyAction><StylePolicyAction name="@@SERVICE_NAME@@Policy_rule_Error_conditional_0_refaction_xform_0" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<Type>xform</Type>
<Input>NULL</Input>
<Transform>local:///dpcommon/xsl/createFault.xsl</Transform>
<ParseSettingsReference>
<URL/>
<Literal/>
<Default/></ParseSettingsReference>
<ParseMetricsResultType>none</ParseMetricsResultType>
<TransformLanguage>none</TransformLanguage>
<ActionDebug persisted="false">off</ActionDebug>
<Output>custvar1</Output>
<NamedInOutLocationType>default</NamedInOutLocationType>
<SSLClientConfigType>proxy</SSLClientConfigType>
<OutputType>default</OutputType>
<Transactional>off</Transactional>
<SOAPValidation>body</SOAPValidation>
<SQLSourceType>static</SQLSourceType>
<JWSVerifyStripSignature>on</JWSVerifyStripSignature>
<Asynchronous>off</Asynchronous>
<ResultsMode>first-available</ResultsMode>
<RetryCount>0</RetryCount>
<RetryInterval>1000</RetryInterval>
<MultipleOutputs>off</MultipleOutputs>
<IteratorType>XPATH</IteratorType>
<Timeout>0</Timeout>
<MethodRewriteType>GET</MethodRewriteType>
<MethodType>POST</MethodType>
<MethodType2>POST</MethodType2></StylePolicyAction><StylePolicyAction name="@@SERVICE_NAME@@Policy_rule_Error_conditional_0_refaction_gatewayscript_0" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<Type>gatewayscript</Type>
<Input>NULL</Input>
<ParseSettingsReference>
<URL/>
<Literal/>
<Default/></ParseSettingsReference>
<ParseMetricsResultType>none</ParseMetricsResultType>
<TransformLanguage>none</TransformLanguage>
<GatewayScriptLocation>local:///dpcommon/js/json_error_handling.js</GatewayScriptLocation>
<ActionDebug persisted="false">off</ActionDebug>
<Output>custvar1</Output>
<NamedInOutLocationType>default</NamedInOutLocationType>
<SSLClientConfigType>proxy</SSLClientConfigType>
<Transactional>off</Transactional>
<SOAPValidation>body</SOAPValidation>
<SQLSourceType>static</SQLSourceType>
<JWSVerifyStripSignature>on</JWSVerifyStripSignature>
<Asynchronous>off</Asynchronous>
<ResultsMode>first-available</ResultsMode>
<RetryCount>0</RetryCount>
<RetryInterval>1000</RetryInterval>
<MultipleOutputs>off</MultipleOutputs>
<IteratorType>XPATH</IteratorType>
<Timeout>0</Timeout>
<MethodRewriteType>GET</MethodRewriteType>
<MethodType>POST</MethodType>
<MethodType2>POST</MethodType2></StylePolicyAction><StylePolicyAction name="@@SERVICE_NAME@@Policy_rule_Error_conditional_0" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<Type>conditional</Type>
<Input>dp_var1</Input>
<ParseSettingsReference>
<URL/>
<Literal/>
<Default/></ParseSettingsReference>
<ParseMetricsResultType>none</ParseMetricsResultType>
<TransformLanguage>none</TransformLanguage>
<ActionDebug persisted="false">off</ActionDebug>
<NamedInOutLocationType>default</NamedInOutLocationType>
<SSLClientConfigType>proxy</SSLClientConfigType>
<Transactional>off</Transactional>
<SOAPValidation>body</SOAPValidation>
<SQLSourceType>static</SQLSourceType>
<JWSVerifyStripSignature>on</JWSVerifyStripSignature>
<Asynchronous>off</Asynchronous>
<Condition>
<Expression>/xml</Expression>
<ConditionAction>@@SERVICE_NAME@@Policy_rule_Error_conditional_0_refaction_xform_0</ConditionAction></Condition>
<Condition>
<Expression>/json</Expression>
<ConditionAction>@@SERVICE_NAME@@Policy_rule_Error_conditional_0_refaction_gatewayscript_0</ConditionAction></Condition>
<ResultsMode>first-available</ResultsMode>
<RetryCount>0</RetryCount>
<RetryInterval>1000</RetryInterval>
<MultipleOutputs>off</MultipleOutputs>
<IteratorType>XPATH</IteratorType>
<Timeout>0</Timeout>
<MethodRewriteType>GET</MethodRewriteType>
<MethodType>POST</MethodType>
<MethodType2>POST</MethodType2></StylePolicyAction><StylePolicyAction name="@@SERVICE_NAME@@Policy_rule_Error_results_output_0" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<Type>results</Type>
<Input>custvar1</Input>
<ParseSettingsReference>
<URL/>
<Literal/>
<Default/></ParseSettingsReference>
<ParseMetricsResultType>none</ParseMetricsResultType>
<TransformLanguage>none</TransformLanguage>
<ActionDebug persisted="false">off</ActionDebug>
<NamedInOutLocationType>default</NamedInOutLocationType>
<SSLClientConfigType>proxy</SSLClientConfigType>
<OutputType>default</OutputType>
<Transactional>off</Transactional>
<SOAPValidation>body</SOAPValidation>
<SQLSourceType>static</SQLSourceType>
<JWSVerifyStripSignature>on</JWSVerifyStripSignature>
<Asynchronous>off</Asynchronous>
<ResultsMode>first-available</ResultsMode>
<RetryCount>0</RetryCount>
<RetryInterval>1000</RetryInterval>
<MultipleOutputs>off</MultipleOutputs>
<IteratorType>XPATH</IteratorType>
<Timeout>0</Timeout>
<MethodRewriteType>GET</MethodRewriteType>
<MethodType>POST</MethodType>
<MethodType2>POST</MethodType2></StylePolicyAction><StylePolicyRule name="@@SERVICE_NAME@@Policy_rule_Error" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<Actions class="StylePolicyAction">@@SERVICE_NAME@@Policy_rule_Error_xform_1</Actions>
<Actions class="StylePolicyAction">@@SERVICE_NAME@@Policy_rule_Error_xform_2</Actions>
<Actions class="StylePolicyAction">@@SERVICE_NAME@@Policy_rule_Error_conditional_0</Actions>
<Actions class="StylePolicyAction">@@SERVICE_NAME@@Policy_rule_Error_results_output_0</Actions>
<Direction>error-rule</Direction>
<InputFormat>none</InputFormat>
<OutputFormat>none</OutputFormat>
<NonXMLProcessing>on</NonXMLProcessing>
<Unprocessed>off</Unprocessed></StylePolicyRule><StylePolicy name="@@SERVICE_NAME@@Policy" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<DefStylesheetForSoap>store:///filter-reject-all.xsl</DefStylesheetForSoap>
<DefStylesheetForXsl>store:///identity.xsl</DefStylesheetForXsl>
<DefXQueryForJSON>store:///reject-all-json.xq</DefXQueryForJSON>
<PolicyMaps>
<Match class="Matching">ALL</Match>
<Rule class="StylePolicyRule">@@SERVICE_NAME@@Policy_RequestRule</Rule></PolicyMaps>
<PolicyMaps>
<Match class="Matching">ALL</Match>
<Rule class="StylePolicyRule">@@SERVICE_NAME@@Policy_ResponseRule</Rule></PolicyMaps>
<PolicyMaps>
<Match class="Matching">ALL</Match>
<Rule class="StylePolicyRule">@@SERVICE_NAME@@Policy_rule_Error</Rule></PolicyMaps></StylePolicy><PolicyAttachments name="@@SERVICE_NAME@@MPG" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<EnforcementMode>enforce</EnforcementMode>
<PolicyReferences>on</PolicyReferences>
<SLAEnforcementMode>allow-if-no-sla</SLAEnforcementMode></PolicyAttachments><MultiProtocolGateway name="@@SERVICE_NAME@@MPG" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<UserSummary>To handle the pass through consumer from AWS to DP</UserSummary>
<Priority>normal</Priority>
<FrontProtocol class="HTTPSSourceProtocolHandler">@@SERVICE_NAME@@HttpsFSH</FrontProtocol>
<XMLManager class="XMLManager">@@SERVICE_NAME@@XMLManager</XMLManager>
<SSLClientConfigType>client</SSLClientConfigType>
<StylesheetParameters>
<ParameterName>ClientOUID</ParameterName>
<ParameterValue>@@SERVICE_CLIENTOUID@@</ParameterValue></StylesheetParameters>
<StylesheetParameters>
<ParameterName>TestOUID</ParameterName>
<ParameterValue>TD</ParameterValue></StylesheetParameters>
<DefaultParamNamespace>http://www.datapower.com/param/config</DefaultParamNamespace>
<QueryParamNamespace>http://www.datapower.com/param/query</QueryParamNamespace>
<PropagateURI>off</PropagateURI>
<MonitorProcessingPolicy>terminate-at-first-throttle</MonitorProcessingPolicy>
<RequestAttachments>strip</RequestAttachments>
<ResponseAttachments>strip</ResponseAttachments>
<RequestAttachmentsFlowControl>off</RequestAttachmentsFlowControl>
<ResponseAttachmentsFlowControl>off</ResponseAttachmentsFlowControl>
<RootPartNotFirstAction>process-in-order</RootPartNotFirstAction>
<FrontAttachmentFormat>dynamic</FrontAttachmentFormat>
<BackAttachmentFormat>dynamic</BackAttachmentFormat>
<MIMEFrontHeaders>on</MIMEFrontHeaders>
<MIMEBackHeaders>on</MIMEBackHeaders>
<StreamOutputToBack>buffer-until-verification</StreamOutputToBack>
<StreamOutputToFront>buffer-until-verification</StreamOutputToFront>
<MaxMessageSize>0</MaxMessageSize>
<GatewayParserLimits>off</GatewayParserLimits>
<ParserLimitsElementDepth>512</ParserLimitsElementDepth>
<ParserLimitsAttributeCount>128</ParserLimitsAttributeCount>
<ParserLimitsMaxNodeSize>33554432</ParserLimitsMaxNodeSize>
<ParserLimitsForbidExternalReferences>on</ParserLimitsForbidExternalReferences>
<ParserLimitsExternalReferences>forbid</ParserLimitsExternalReferences>
<ParserLimitsMaxPrefixes>1024</ParserLimitsMaxPrefixes>
<ParserLimitsMaxNamespaces>1024</ParserLimitsMaxNamespaces>
<ParserLimitsMaxLocalNames>60000</ParserLimitsMaxLocalNames>
<ParserLimitsAttachmentByteCount>2000000000</ParserLimitsAttachmentByteCount>
<ParserLimitsAttachmentPackageByteCount>0</ParserLimitsAttachmentPackageByteCount>
<DebugMode persisted="false">on</DebugMode>
<DebuggerType>internal</DebuggerType>
<DebugHistory>25</DebugHistory>
<FlowControl>off</FlowControl>
<SOAPSchemaURL>store:///schemas/soap-envelope.xsd</SOAPSchemaURL>
<FrontTimeout>120</FrontTimeout>
<BackTimeout>120</BackTimeout>
<FrontPersistentTimeout>180</FrontPersistentTimeout>
<BackPersistentTimeout>180</BackPersistentTimeout>
<IncludeResponseTypeEncoding>on</IncludeResponseTypeEncoding>
<BackHTTPVersion>HTTP/1.1</BackHTTPVersion>
<PersistentConnections>on</PersistentConnections>
<LoopDetection>off</LoopDetection>
<DoHostRewriting>on</DoHostRewriting>
<DoChunkedUpload>off</DoChunkedUpload>
<ProcessHTTPErrors>on</ProcessHTTPErrors>
<HTTPClientIPLabel>X-Client-IP</HTTPClientIPLabel>
<HTTPLogCorIDLabel>X-Global-Transaction-ID</HTTPLogCorIDLabel>
<InOrderMode>
<Request>off</Request>
<Backend>off</Backend>
<Response>off</Response></InOrderMode>
<WSAMode>sync2sync</WSAMode>
<WSARequireAAA>on</WSARequireAAA>
<WSAStrip>on</WSAStrip>
<WSADefaultReplyTo>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</WSADefaultReplyTo>
<WSADefaultFaultTo>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</WSADefaultFaultTo>
<WSAForce>off</WSAForce>
<WSAGenStyle>sync</WSAGenStyle>
<WSAHTTPAsyncResponseCode>204</WSAHTTPAsyncResponseCode>
<WSATimeout>120</WSATimeout>
<WSRMEnabled>off</WSRMEnabled>
<WSRMSequenceExpiration>3600</WSRMSequenceExpiration>
<WSRMDestinationAcceptCreateSequence>on</WSRMDestinationAcceptCreateSequence>
<WSRMDestinationMaximumSequences>400</WSRMDestinationMaximumSequences>
<WSRMDestinationInOrder>off</WSRMDestinationInOrder>
<WSRMDestinationMaximumInOrderQueueLength>10</WSRMDestinationMaximumInOrderQueueLength>
<WSRMDestinationAcceptOffers>off</WSRMDestinationAcceptOffers>
<WSRMFrontForce>off</WSRMFrontForce>
<WSRMBackForce>off</WSRMBackForce>
<WSRMBackCreateSequence>off</WSRMBackCreateSequence>
<WSRMFrontCreateSequence>off</WSRMFrontCreateSequence>
<WSRMSourceMakeOffer>off</WSRMSourceMakeOffer>
<WSRMUsesSequenceSSL>off</WSRMUsesSequenceSSL>
<WSRMSourceMaximumSequences>400</WSRMSourceMaximumSequences>
<WSRMSourceRetransmissionInterval>10</WSRMSourceRetransmissionInterval>
<WSRMSourceExponentialBackoff>on</WSRMSourceExponentialBackoff>
<WSRMSourceMaximumRetransmissions>4</WSRMSourceMaximumRetransmissions>
<WSRMSourceMaximumQueueLength>30</WSRMSourceMaximumQueueLength>
<WSRMSourceRequestAckCount>1</WSRMSourceRequestAckCount>
<WSRMSourceInactivityClose>360</WSRMSourceInactivityClose>
<ForcePolicyExec>on</ForcePolicyExec>
<RewriteErrors>on</RewriteErrors>
<DelayErrors>on</DelayErrors>
<DelayErrorsDuration>1000</DelayErrorsDuration>
<RequestType>preprocessed</RequestType>
<ResponseType>preprocessed</ResponseType>
<FollowRedirects>on</FollowRedirects>
<RewriteLocationHeader>off</RewriteLocationHeader>
<StylePolicy class="StylePolicy">@@SERVICE_NAME@@Policy</StylePolicy>
<Type>dynamic-backend</Type>
<AllowCompression>off</AllowCompression>
<AllowCacheControlHeader>off</AllowCacheControlHeader>
<PolicyAttachments class="PolicyAttachments">@@SERVICE_NAME@@MPG</PolicyAttachments>
<WSMAgentMonitor>off</WSMAgentMonitor>
<WSMAgentMonitorPCM>all-messages</WSMAgentMonitorPCM>
<ProxyHTTPResponse>off</ProxyHTTPResponse>
<TransactionTimeout>0</TransactionTimeout></MultiProtocolGateway></configuration><files><file name="store:///healthcheck.xml" src="store/healthcheck.xml" location="store" hash="LvIzTFgKgCrtz8VptDaqwCgWN0I="/><file name="store:///healthcheck.json" src="store/healthcheck.json" location="store" hash="vyGp6PvFo4RvsFtPoIWeCReyIC8="/><file name="store:///healthcheck.js" src="store/healthcheck.js" location="store" hash="bN8DS27FK8uny6ZxR8NJ6pWngRM="/><file name="local:///dpcommon/xsl/bmo-transaction-log.xsl" src="local/dpcommon/xsl/bmo-transaction-log.xsl" location="local" hash="2hNGBWeR4lmY6i8S+HV8d7MQfAk="/><file name="local:///mpg/SmartcoreServicesV1/@@SERVICE_NAME@@MPG/xsl/ClientAuthentication.xsl" src="local/mpg/SmartcoreServicesV1/@@SERVICE_NAME@@MPG/xsl/ClientAuthentication.xsl" location="local" hash="GnmS6Ne76Fpeeg64x+5CSJ8QLOA="/><file name="local:///mpg/SmartcoreServicesV1/@@SERVICE_NAME@@MPG/xsl/payloadSizeValidation.xsl" src="local/mpg/SmartcoreServicesV1/@@SERVICE_NAME@@MPG/xsl/payloadSizeValidation.xsl" location="local" hash="OvvMOcjf8Lo20vA9k8KqjhK6b/k="/><file name="local:///mpg/SmartcoreServicesV1/@@SERVICE_NAME@@MPG/xsl/process.xsl" src="local/mpg/SmartcoreServicesV1/@@SERVICE_NAME@@MPG/xsl/process.xsl" location="local" hash="oZkBUWk5B93eEgr8ys28EvBFzJ8="/><file name="local:///dpcommon/xsl/setResponseCode.xsl" src="local/dpcommon/xsl/setResponseCode.xsl" location="local" hash="5ax8FCCTRpOwuD5xB+0xdMHFLak="/><file name="local:///mpg/SmartcoreServicesV1/@@SERVICE_NAME@@MPG/xsl/chooseMessageType.xsl" src="local/mpg/SmartcoreServicesV1/@@SERVICE_NAME@@MPG/xsl/chooseMessageType.xsl" location="local" hash="Rx1HWgq8nCXi7nvwaYb90lx+41U="/><file name="local:///dpcommon/xsl/createFault.xsl" src="local/dpcommon/xsl/createFault.xsl" location="local" hash="G++zNgZTB6yshsEmBYDuKG5g6ik="/><file name="local:///dpcommon/js/json_error_handling.js" src="local/dpcommon/js/json_error_handling.js" location="local" hash="DM+Rt9cof4vGlF3/mdg4KxymTzI="/><file name="webgui:///clixform.xsl" src="dp-aux/clixform.xsl" location="dp-aux" internal="true" hash="5D6rHcHlxffHkL6WqXFk5rM/MSw="/><file name="webgui:///SchemaUtil.xsl" src="dp-aux/SchemaUtil.xsl" location="dp-aux" internal="true" hash="ZnCYHBrcIPvfLAXYOIKIL0KXIbo="/><file name="webgui:///management.xsl" src="dp-aux/management.xsl" location="dp-aux" internal="true" hash="pi0c46mGrlbqTpsWjG3QUxFOCYU="/><file name="webgui:///map-dmz.xsl" src="dp-aux/map-dmz.xsl" location="dp-aux" internal="true" hash="S8LbpfukTeInHK2d6DnQfdiZmd4="/><file name="webgui:///drMgmt.xml" src="dp-aux/drMgmt.xml" location="dp-aux" internal="true" hash="6fYaKg4C6F9rrSHc5VotBh+DVXg="/><file name="webgui:///basetypes.xml" src="dp-aux/basetypes.xml" location="dp-aux" internal="true" hash="HrLsg2FhC6fPlGYI25NijeP828E="/></files></datapower-configuration>
