<datapower-configuration version="3"><export-details><description>Exported Configuration</description><user>twu04</user><domain>DIT-Common-Services</domain><comment/><product-id>5725</product-id><product>IDG</product><display-product>IDG</display-product><model>IBM DataPower Gateway</model><display-model>IBM DataPower Gateway</display-model><device-name>ciambccudtdpw01</device-name><serial-number>0000000</serial-number><firmware-version>IDG.2018.4.1.3hy</firmware-version><display-firmware-version>IDG.2018.4.1.3hy</display-firmware-version><firmware-build>307450hy</firmware-build><delivery-type>LTS</delivery-type><firmware-timestamp>2019/03/23 13:30:08</firmware-timestamp><current-date>2020-03-31</current-date><current-time>17:16:48 EDT</current-time><reset-date>2020-03-25</reset-date><reset-time>00:45:36 EDT</reset-time><login-message/><custom-ui-file>local:///DP_Banner.xml</custom-ui-file></export-details><interface-data/><configuration domain="DIT-Common-Services"><HTTPSourceProtocolHandler name="BHOBAuditLoggerHttpFSH" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<LocalAddress>Data_Localhost</LocalAddress>
<LocalPort>8110</LocalPort>
<HTTPVersion>HTTP/1.1</HTTPVersion>
<AllowedFeatures>
<HTTP-1.0>on</HTTP-1.0>
<HTTP-1.1>on</HTTP-1.1>
<HTTP-2.0>off</HTTP-2.0>
<POST>on</POST>
<GET>on</GET>
<PUT>on</PUT>
<HEAD>off</HEAD>
<OPTIONS>off</OPTIONS>
<TRACE>off</TRACE>
<DELETE>on</DELETE>
<CONNECT>off</CONNECT>
<CustomMethods>off</CustomMethods>
<QueryString>on</QueryString>
<FragmentIdentifiers>on</FragmentIdentifiers>
<DotDot>off</DotDot>
<CmdExe>off</CmdExe></AllowedFeatures>
<PersistentConnections>on</PersistentConnections>
<MaxPersistentConnectionsReuse>0</MaxPersistentConnectionsReuse>
<AllowCompression>off</AllowCompression>
<AllowWebSocketUpgrade>off</AllowWebSocketUpgrade>
<WebSocketIdleTimeout>0</WebSocketIdleTimeout>
<MaxURLLen>16384</MaxURLLen>
<MaxTotalHdrLen>128000</MaxTotalHdrLen>
<MaxHdrCount>0</MaxHdrCount>
<MaxNameHdrLen>0</MaxNameHdrLen>
<MaxValueHdrLen>0</MaxValueHdrLen>
<MaxQueryStringLen>0</MaxQueryStringLen>
<CredentialCharset>protocol</CredentialCharset>
<HTTP2MaxStreams>100</HTTP2MaxStreams>
<HTTP2MaxFrameSize>16384</HTTP2MaxFrameSize>
<HTTP2StreamHeader>off</HTTP2StreamHeader>
<ChunkedEncoding>on</ChunkedEncoding></HTTPSourceProtocolHandler><HTTPUserAgent name="default" intrinsic="true" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<UserSummary>Default User Agent</UserSummary>
<MaxRedirects>8</MaxRedirects>
<Timeout>300</Timeout></HTTPUserAgent><XMLManager name="default" intrinsic="true" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<UserSummary>Default XML-Manager</UserSummary>
<CacheSize>256</CacheSize>
<SHA1Caching>on</SHA1Caching>
<StaticDocumentCalls>on</StaticDocumentCalls>
<SearchResults>on</SearchResults>
<SupportTxWarn>off</SupportTxWarn>
<Memoization>on</Memoization>
<ParserLimitsBytesScanned>@@SERVICE_PAYLOAD_SIZE@@</ParserLimitsBytesScanned>
<ParserLimitsElementDepth>512</ParserLimitsElementDepth>
<ParserLimitsAttributeCount>128</ParserLimitsAttributeCount>
<ParserLimitsMaxNodeSize>33554432</ParserLimitsMaxNodeSize>
<ParserLimitsForbidExternalReferences>on</ParserLimitsForbidExternalReferences>
<ParserLimitsExternalReferences>forbid</ParserLimitsExternalReferences>
<ParserLimitsMaxPrefixes>1024</ParserLimitsMaxPrefixes>
<ParserLimitsMaxNamespaces>1024</ParserLimitsMaxNamespaces>
<ParserLimitsMaxLocalNames>60000</ParserLimitsMaxLocalNames>
<DocCacheMaxDocs>5000</DocCacheMaxDocs>
<DocCacheSize>0</DocCacheSize>
<DocMaxWrites>32768</DocMaxWrites>
<UserAgent class="HTTPUserAgent">default</UserAgent></XMLManager><StylePolicy name="default" intrinsic="true" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<UserSummary>Default Processing Policy</UserSummary>
<DefStylesheetForSoap>store:///filter-reject-all.xsl</DefStylesheetForSoap>
<DefStylesheetForXsl>store:///identity.xsl</DefStylesheetForXsl>
<DefXQueryForJSON>store:///reject-all-json.xq</DefXQueryForJSON></StylePolicy><MultiProtocolGateway name="@@SERVICE_NAME@@MPG" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
<mAdminState>enabled</mAdminState>
<UserSummary>@@SERVICE_FLOW@@</UserSummary>
<Priority>normal</Priority>
<FrontProtocol class="HTTPSourceProtocolHandler">BHOBAuditLoggerHttpFSH</FrontProtocol>
<XMLManager class="XMLManager">default</XMLManager>
<SSLClientConfigType>proxy</SSLClientConfigType>
<DefaultParamNamespace>http://www.datapower.com/param/config</DefaultParamNamespace>
<QueryParamNamespace>http://www.datapower.com/param/query</QueryParamNamespace>
<BackendUrl>@@BACKEND_URL@@</BackendUrl>
<PropagateURI>on</PropagateURI>
<MonitorProcessingPolicy>terminate-at-first-throttle</MonitorProcessingPolicy>
<RequestAttachments>strip</RequestAttachments>
<ResponseAttachments>strip</ResponseAttachments>
<RequestAttachmentsFlowControl>off</RequestAttachmentsFlowControl>
<ResponseAttachmentsFlowControl>off</ResponseAttachmentsFlowControl>
<RootPartNotFirstAction>process-in-order</RootPartNotFirstAction>
<FrontAttachmentFormat>dynamic</FrontAttachmentFormat>
<BackAttachmentFormat>dynamic</BackAttachmentFormat>
<MIMEFrontHeaders>on</MIMEFrontHeaders>
<MIMEBackHeaders>on</MIMEBackHeaders>
<StreamOutputToBack>buffer-until-verification</StreamOutputToBack>
<StreamOutputToFront>buffer-until-verification</StreamOutputToFront>
<MaxMessageSize>0</MaxMessageSize>
<GatewayParserLimits>off</GatewayParserLimits>
<ParserLimitsElementDepth>512</ParserLimitsElementDepth>
<ParserLimitsAttributeCount>128</ParserLimitsAttributeCount>
<ParserLimitsMaxNodeSize>33554432</ParserLimitsMaxNodeSize>
<ParserLimitsForbidExternalReferences>on</ParserLimitsForbidExternalReferences>
<ParserLimitsExternalReferences>forbid</ParserLimitsExternalReferences>
<ParserLimitsMaxPrefixes>1024</ParserLimitsMaxPrefixes>
<ParserLimitsMaxNamespaces>1024</ParserLimitsMaxNamespaces>
<ParserLimitsMaxLocalNames>60000</ParserLimitsMaxLocalNames>
<ParserLimitsAttachmentByteCount>2000000000</ParserLimitsAttachmentByteCount>
<ParserLimitsAttachmentPackageByteCount>0</ParserLimitsAttachmentPackageByteCount>
<DebugMode persisted="false">off</DebugMode>
<DebuggerType>internal</DebuggerType>
<DebugHistory>25</DebugHistory>
<FlowControl>off</FlowControl>
<SOAPSchemaURL>store:///schemas/soap-envelope.xsd</SOAPSchemaURL>
<FrontTimeout>@@SERVICE_TIMEOUT@@</FrontTimeout>
<BackTimeout>@@SERVICE_TIMEOUT@@</BackTimeout>
<FrontPersistentTimeout>180</FrontPersistentTimeout>
<BackPersistentTimeout>180</BackPersistentTimeout>
<IncludeResponseTypeEncoding>off</IncludeResponseTypeEncoding>
<BackHTTPVersion>HTTP/1.1</BackHTTPVersion>
<PersistentConnections>on</PersistentConnections>
<LoopDetection>off</LoopDetection>
<DoHostRewriting>on</DoHostRewriting>
<DoChunkedUpload>off</DoChunkedUpload>
<ProcessHTTPErrors>on</ProcessHTTPErrors>
<HTTPClientIPLabel>X-Client-IP</HTTPClientIPLabel>
<HTTPLogCorIDLabel>X-Global-Transaction-ID</HTTPLogCorIDLabel>
<InOrderMode>
<Request>off</Request>
<Backend>off</Backend>
<Response>off</Response></InOrderMode>
<WSAMode>sync2sync</WSAMode>
<WSARequireAAA>on</WSARequireAAA>
<WSAStrip>on</WSAStrip>
<WSADefaultReplyTo>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</WSADefaultReplyTo>
<WSADefaultFaultTo>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</WSADefaultFaultTo>
<WSAForce>off</WSAForce>
<WSAGenStyle>sync</WSAGenStyle>
<WSAHTTPAsyncResponseCode>204</WSAHTTPAsyncResponseCode>
<WSATimeout>120</WSATimeout>
<WSRMEnabled>off</WSRMEnabled>
<WSRMSequenceExpiration>3600</WSRMSequenceExpiration>
<WSRMDestinationAcceptCreateSequence>on</WSRMDestinationAcceptCreateSequence>
<WSRMDestinationMaximumSequences>400</WSRMDestinationMaximumSequences>
<WSRMDestinationInOrder>off</WSRMDestinationInOrder>
<WSRMDestinationMaximumInOrderQueueLength>10</WSRMDestinationMaximumInOrderQueueLength>
<WSRMDestinationAcceptOffers>off</WSRMDestinationAcceptOffers>
<WSRMFrontForce>off</WSRMFrontForce>
<WSRMBackForce>off</WSRMBackForce>
<WSRMBackCreateSequence>off</WSRMBackCreateSequence>
<WSRMFrontCreateSequence>off</WSRMFrontCreateSequence>
<WSRMSourceMakeOffer>off</WSRMSourceMakeOffer>
<WSRMUsesSequenceSSL>off</WSRMUsesSequenceSSL>
<WSRMSourceMaximumSequences>400</WSRMSourceMaximumSequences>
<WSRMSourceRetransmissionInterval>10</WSRMSourceRetransmissionInterval>
<WSRMSourceExponentialBackoff>on</WSRMSourceExponentialBackoff>
<WSRMSourceMaximumRetransmissions>4</WSRMSourceMaximumRetransmissions>
<WSRMSourceMaximumQueueLength>30</WSRMSourceMaximumQueueLength>
<WSRMSourceRequestAckCount>1</WSRMSourceRequestAckCount>
<WSRMSourceInactivityClose>360</WSRMSourceInactivityClose>
<ForcePolicyExec>off</ForcePolicyExec>
<RewriteErrors>on</RewriteErrors>
<DelayErrors>on</DelayErrors>
<DelayErrorsDuration>1000</DelayErrorsDuration>
<RequestType>soap</RequestType>
<ResponseType>soap</ResponseType>
<FollowRedirects>on</FollowRedirects>
<RewriteLocationHeader>off</RewriteLocationHeader>
<StylePolicy class="StylePolicy">default</StylePolicy>
<Type>static-backend</Type>
<AllowCompression>off</AllowCompression>
<AllowCacheControlHeader>off</AllowCacheControlHeader>
<WSMAgentMonitor>off</WSMAgentMonitor>
<WSMAgentMonitorPCM>all-messages</WSMAgentMonitorPCM>
<ProxyHTTPResponse>off</ProxyHTTPResponse>
<TransactionTimeout>0</TransactionTimeout></MultiProtocolGateway></configuration><files><file name="webgui:///clixform.xsl" src="dp-aux/clixform.xsl" location="dp-aux" internal="true" hash="5D6rHcHlxffHkL6WqXFk5rM/MSw="/><file name="webgui:///SchemaUtil.xsl" src="dp-aux/SchemaUtil.xsl" location="dp-aux" internal="true" hash="ZnCYHBrcIPvfLAXYOIKIL0KXIbo="/><file name="webgui:///management.xsl" src="dp-aux/management.xsl" location="dp-aux" internal="true" hash="pi0c46mGrlbqTpsWjG3QUxFOCYU="/><file name="webgui:///map-dmz.xsl" src="dp-aux/map-dmz.xsl" location="dp-aux" internal="true" hash="S8LbpfukTeInHK2d6DnQfdiZmd4="/><file name="webgui:///drMgmt.xml" src="dp-aux/drMgmt.xml" location="dp-aux" internal="true" hash="6fYaKg4C6F9rrSHc5VotBh+DVXg="/><file name="webgui:///basetypes.xml" src="dp-aux/basetypes.xml" location="dp-aux" internal="true" hash="HrLsg2FhC6fPlGYI25NijeP828E="/></files></datapower-configuration>
